#!/usr/bin/env Rscript

sys = modules::import('klmr/sys')

sys$run({
    args = list(genes = 'data/repeat-quant/genes-ms-vs-co.tsv',
                mode = 'background',
                annotation = 'data/annotation/Mus_musculus.GRCm38.75.repeats.gtf',
                output = 'data/reference/Mus_musculus.GRCm38.75.repeats.upstream.fasta')

    modules::import_package('dplyr', attach = TRUE)

    mcols = GenomicRanges::mcols

    genes = readr::read_tsv(args$genes)
    annotation = rtracklayer::import(args$annotation)
    annotation = annotation[mcols(annotation)$Name %in% unique(genes$Gene)]
})

# vim: ft=r
