#!/usr/bin/env bash

input="$1"
reference="$2"
output="$3"

# Write a readable name into the “feature” column that is used by bedtools
# to name the Fasta records when specifying the `-name` flag.
gff-rename() {
    < "$1" \
    awk -F $'\t' -vOFS=$'\t' '{
        match($9, /Name="[^"]*"/)
        feature_name = substr($9, RSTART + 6, RLENGTH - 7)
        match($9, /Derives_from="[^"]*"/)
        feature_name = feature_name " " substr($9, RSTART, RLENGTH)
        print $1, $2, feature_name, $4, $5, $6, $7, $8, $9
    }'
}

bedtools getfasta -name -fi "$reference" -bed <(gff-rename "$input") -fo "$output"
