#!/usr/bin/env Rscript

sys = modules::import('klmr/sys')

sys$run({
    vst_expression = readr::read_tsv('data/repeat-quant/vsd-ms-vs-co.tsv')
    sorted_results = readr::read_tsv('data/repeat-quant/genes-ms-vs-co.tsv')
    samples = readr::read_tsv('data/repeat-quant/samples.tsv')

    modules::import_package('dplyr', attach = TRUE)
    modules::import_package('tidyr', attach = TRUE)
    modules::import('klmr/ggplots', attach = TRUE)

    theme_set(theme_publication)

    alpha = 0.05

    de_genes = vst_expression %>%
        inner_join(sorted_results, by = 'Gene') %>%
        filter(padj < alpha) %>%
        gather(Sample, Expression, -Gene, -log2FoldChange, -padj) %>%
        inner_join(samples, by = c(Sample = 'ID')) %>%
        select(Gene, Group, Expression, log2FoldChange, padj) %>%
        group_by(Gene, Group) %>%
        mutate(Mean = mean(Expression)) %>%
        ungroup() %>%
        mutate(Gene = gsub('-', '­', Gene),
               Gene = factor(Gene, unique(Gene)[order(unique(log2FoldChange))],
                             ordered = TRUE))

    annotation = rtracklayer::import('data/annotation/Mus_musculus.GRCm38.75.repeats.gtf') %>%
        GenomicRanges::mcols %>%
        as_data_frame() %>%
        select(Name, Class = Derives_from) %>%
        group_by(Name, Class) %>%
        summarize()

    gene_changes = de_genes %>%
        group_by(Gene, Group) %>%
        summarize(Mean = first(Mean), log2FoldChange = first(log2FoldChange)) %>%
        spread(Group, Mean) %>%
        inner_join(annotation, by = c(Gene = 'Name')) %>%
        ungroup() %>%
        separate(Class, c('Order', 'Name'), '/', remove = FALSE) %>%
        mutate(Name = sub('-.*', '', Name)) %>%
        mutate(Gene = reorder(Gene, log2FoldChange))

    log2_breaks = function (x) {
        breaks = scales::log_breaks(base = 2)(x)
        # Interpolate more point between even log breaks
        sort(c(breaks, na.omit(rowMeans(cbind(breaks, lag(breaks))))))
    }

    gene_change_labels = gene_changes %>%
        with(sprintf('%s\n(%s)', Class, Gene))

    p = ggplot(gene_changes) +
        aes(x = Gene, xend = Gene, y = co, yend = ms, color = Order, alpha = log2FoldChange) %>%
        geom_segment(lwd = 0.8,
                     arrow = arrow(length = unit(0.08, 'inches'), type = 'closed')) +
        scale_y_continuous(breaks = log2_breaks, trans = scales::log2_trans()) +
        scale_x_discrete(labels = gene_change_labels) +
        scale_alpha(range = c(0.3, 1)) +
        theme(axis.text.x = element_text(angle = 45, hjust = 1, size = 8)) +
        labs(x = 'Repeat element', y = 'Expression (arb. unit)',
             alpha = expression(paste(log[2], FC))) +
        ggtitle('Significant gene expression changes',
                'Direction of gene expression change (from control to treatment) is indicated by the arrow; magnitude is indicated by the size and opacity of the arrow')

    ggsave('data/repeat-quant/te-changes.pdf', p, width = 10, height = 5)
    fonts$embed('data/repeat-quant/te-changes.pdf')
})

# vim: ft=r
