#!/usr/bin/env perl

use strict;
use warnings;

my $counter = 0;
my $id;
my $seq = '';

while (<>) {
    $counter = ($counter + 1) % 4;
    if ($counter == 1) {
        $id = $_;
    } elsif ($counter == 2) {
        if (s/CCA$//) {
            $seq = $_;
        }
    } elsif ($counter == 0) {
        if ($seq ne '') {
            chomp;
            my $qual = substr($_, 0, -3);
            print "$id$seq+\n$qual\n";
            $seq = '';
        }
    }
}
