#!/usr/bin/env perl

use strict;
use warnings;

my $counter = 0;
my $cut = 0;

while (<>) {
    $counter = ($counter + 1) % 4;
    if ($counter == 2) {
        $cut = 1 if (s/CCA$//)
    } elsif ($counter == 0) {
        if ($cut == 1) {
            chomp;
            $_ = substr($_, 0, -3) . "\n";
            $cut = 0;
        }
    }
    print $_;
}
